version: "3"
services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${PG_USERNAME} # change db user
      - POSTGRES_PASSWORD=${PG_PASSWORD} # change db password
      - POSTGRES_DB=${PG_DB} # change default database that is created when the image is first started. 
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql # create init table and data
      - pg-data:/var/lib/postgresql/data # map persistent data
      # or mount to host path
      #- ./data:/var/lib/postgresql/data

volumes:
  pg-data:
  