version: '3.1'
services:
  web:
    image: httpd
    ports:
      - '8080:80'
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    restart: always
    environment:
      - VIRTUAL_HOST=web.com,172.16.4.75
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=web.com

networks:
  default:
    external:
      name: webproxy
