version: "3.1"

services:
  db:
    image: postgres:9.4
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: flectra
      # POSTGRES_DB: hosos
    volumes:
      - pg-flectra:/var/lib/postgresql/data

  flectra:
    image: flectrahq/flectra
    restart: always
    ports:
      - 7073:7073
    environment:
      - HOST=db
      - PORT=5432
      - USER=flectra
      - PASSWORD=flectra
    # volumes:
    #   - /path/to/config:/etc/flectra
    #   - /path/to/addons:/mnt/extra-addons
    depends_on:
      - db

volumes:
  pg-flectra:
