version: "3.1"

services:
  # postgres:
  #   image: postgres:10
  #   restart: always
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: pg-user
  #     POSTGRES_PASSWORD: pg-pwd
  #     POSTGRES_DB: hosos
  #   volumes: 
  #     - pg-data:/var/lib/postgresql/data
  #   networks: 
  #     - hospital-os
  
  influxdb:
    image: influxdb
    restart: always
    # ports:
    #   - 8086:8086
    #   - 8088:8088
    # environment:
    #   - INFLUXDB_DB=db0
    #   - INFLUXDB_ADMIN_ENABLED=true
    #   - INFLUXDB_ADMIN_USER=admin
    #   - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
    #   - INFLUXDB_USER=telegraf
    #   - INFLUXDB_USER_PASSWORD=secretpassword
    volumes: 
      - influxdb-data:/var/lib/influxdb
    networks: 
      - influxdb
    # command: ["influxdb", "/init-influxdb.sh"]
  
  telegraf:
    image: telegraf
    restart: always
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    volumes: 
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks: 
      - frontend
      # - hospital-os
      - influxdb
    depends_on: 
      # - postgres
      - influxdb

  chronograf:
    image: chronograf
    restart: always
    ports:
      - 8888:8888
    volumes: 
      - chronograf-data:/var/lib/chronograf
    networks: 
      - frontend
      - influxdb
    depends_on: 
      - influxdb

  kapacitor:
    image: kapacitor
    restart: always
    ports:
      - 9092:9092
    environment: 
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    volumes: 
      # - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - kapacitor-data:/var/lib/kapacitor
    networks: 
      - frontend
      - influxdb
    depends_on: 
      - influxdb

networks:
  # hospital-os:
  frontend:
  influxdb:

volumes: 
  # pg-data:
  influxdb-data:
  chronograf-data:
  kapacitor-data: