version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-raksakol@raksakol.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-Raksakol1446}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
      - pga4volume:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - db


volumes:
  pga4volume:
  
networks:
  default:
    external: true
    name: webproxy
  db:
    external: true
    name: db

