version: '3'
services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - '${PG_PORT:-5432}:5432'
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
      - POSTGRES_USER=${PG_USERNAME} # change db user
      - POSTGRES_PASSWORD=${PG_PASSWORD} # change db password
      - POSTGRES_DB=${PG_DB} # change default database that is created when the image is first started.
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql # create init table and data
      - pg-data:/var/lib/postgresql/data # map persistent data
      # or mount to host path
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '${PGADMIN_PORT:-8080}:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@mail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin1234}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
      - pga4volume:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
volumes:
  pga4volume:
  pg-data:
